esphome:
  name: env-basement-hp
  friendly_name: Basement Heat Pump

esp32:
  board: esp32-c3-devkitm-1

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

captive_portal:

# This is a minimal example of what's required to get things up and
# running.  See the wiki here: 
# https://github.com/Sammy1Am/mitsubishi-uart/wiki/Getting-Started
# for more detailed configuration options

external_components:
  - source:
      type: git
      url: https://github.com/Sammy1Am/mitsubishi-uart
      ref: release # Use "main" to get the latest changes

# Mitsubishi UART Component
mitsubishi_uart:
  heatpump_uart: hp_uart

# Define UART connected to heat pump
uart:
  - id: hp_uart
    baud_rate: 2400 # Default for many Mitsubishi systems
    parity: EVEN # Default for many Mitsubishi systems
    rx_pin:
      number: GPIO6
    tx_pin:
      number: GPIO7
